<?php
namespace app\models;


use yii\db\ActiveRecord;

class Categories extends ActiveRecord
{
    public static function tableName()
    {
        return "categories";
    }
    public  function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'unique'],
            [['name'], 'string']
        ];
    }
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Category Name'
        ]; // TODO: Change the autogenerated stub
    }
    public function getProducts()
    {
        return $this->hasMany(Product::class, ['category_id'=>'id']);

    }

}