<?php
namespace app\models;


use yii\db\ActiveRecord;

class Variation extends ActiveRecord
{
    public static function tableName()
    {
        return "variation";
    }
    public  function rules()
    {
        return [
            [['name', 'size'], 'required'],
            [['name'], 'unique'],
            [['name'], 'string'],
            [['size'], 'integer']

        ];
    }
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => ' Name'
        ]; // TODO: Change the autogenerated stub
    }
    public function getProducts()
    {
        return $this->hasMany(Variation::class, ['product_id'=>'id']);

    }

}